[package]
name = "arco-xpress"
version = { workspace = true }
description = "FICO Xpress solver backend for Arco optimization"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
arco-model = { workspace = true }
arco-expr = { workspace = true }
arco-contracts = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
