[package]
name = "arco-model"
version = { workspace = true }
description = "Canonical Arco model"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[features]
default = ["serde"]
serde = ["dep:serde"]

[dependencies]
smallvec = { workspace = true }
tracing = { workspace = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { workspace = true }
