[package]
name = "arco-cli"
version = { workspace = true }
description = "CLI compiler and solver for KDL optimization models"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = "licenses/BSD-3-Clause.txt"
publish = false
autobins = false
default-run = "arco"

[package.metadata.dist]
# This is the main distributable artifact
dist = true

[[bin]]
name = "arco"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
arco-kdl = { workspace = true }
arco-core = { workspace = true }
arco-highs = { workspace = true }
arco-xpress = { workspace = true, optional = true }
clap = { version = "4", features = ["derive"] }
miette = { version = "7", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { workspace = true }
sysinfo = { workspace = true }
thiserror = "2.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[dev-dependencies]
csv = "1.4"

[features]
default = []
xpress = ["dep:arco-xpress"]
