[package]
name = "arco-python"
version = { workspace = true }
description = "Bindings of arco for Python"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lib]
name = "arco"
crate-type = ["cdylib"]
test = false

[dependencies]
pyo3 = { workspace = true, features = ["extension-module"] }
pyo3-macros = { workspace = true }
arco-python-core = { workspace = true }
arco-python-types = { workspace = true }
arco-solver = { workspace = true, default-features = false }
tracing = { workspace = true }
tracing-subscriber = { workspace = true, default-features = false, features = [
  "ansi",
  "env-filter",
  "fmt",
  "json",
] }

[features]
default = ["scip", "xpress"]
ipopt = ["arco-python-core/ipopt"]
scip = ["arco-python-core/scip"]
xpress = ["arco-python-core/xpress"]

[lints]
workspace = true
