#[path = "arrays.rs"]
pub(crate) mod arrays;
#[path = "bounds.rs"]
pub(crate) mod bounds;
#[path = "constraint.rs"]
pub(crate) mod constraint;
#[path = "enums.rs"]
pub(crate) mod enums;
#[path = "errors.rs"]
pub(crate) mod errors;
#[path = "expr.rs"]
pub(crate) mod expr;
#[path = "handles.rs"]
pub(crate) mod handles;
#[path = "helpers.rs"]
pub(crate) mod helpers;
#[path = "index_set.rs"]
pub(crate) mod index_set;
#[path = "iterators.rs"]
pub(crate) mod iterators;
#[path = "logging.rs"]
pub(crate) mod logging;
#[path = "model_blocks.rs"]
pub(crate) mod model_blocks;
#[path = "model_edit.rs"]
pub(crate) mod model_edit;
#[path = "model_init.rs"]
pub(crate) mod model_init;
#[path = "model_inspect.rs"]
pub(crate) mod model_inspect;
#[cfg(feature = "ipopt")]
#[path = "model_nlp.rs"]
pub(crate) mod model_nlp;
#[path = "model_pretty.rs"]
pub(crate) mod model_pretty;
#[path = "model_solve.rs"]
pub(crate) mod model_solve;
#[cfg(feature = "ipopt")]
#[path = "nonlinear.rs"]
pub(crate) mod nonlinear;
#[cfg(feature = "ipopt")]
#[path = "nonlinear_state.rs"]
pub(crate) mod nonlinear_state;
#[path = "serde_bridge.rs"]
pub(crate) mod serde_bridge;
#[path = "slack_variable.rs"]
pub(crate) mod slack_variable;
#[path = "snapshot.rs"]
pub(crate) mod snapshot;
#[path = "solution.rs"]
pub(crate) mod solution;
#[path = "solver.rs"]
pub(crate) mod solver;
#[path = "variable.rs"]
pub(crate) mod variable;
#[path = "views.rs"]
pub(crate) mod views;
