[package]
name = "arco-scip"
version = { workspace = true }
description = "SCIP external-process solver integration for Arco"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[features]
default = ["diagnostics"]
diagnostics = ["arco-format/diagnostics", "dep:miette"]

[dependencies]
arco-solver = { workspace = true, default-features = false }
arco-format = { workspace = true, default-features = false }
arco-model = { workspace = true, default-features = false }
miette = { version = "7", default-features = false, features = [
  "derive",
], optional = true }
russcip = { version = "0.9.1", default-features = false, features = [
  "bundled",
] }
tracing = { workspace = true }
