[package]
name = "arco-highs"
version = { workspace = true }
description = "HiGHS solver adapter for Arco model views"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
arco-solver = { workspace = true }
arco-model = { workspace = true }
highs = "2.1"
highs-sys = { version = "=1.15.0", features = ["discover"] }
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
