[package]
name = "arco-highs"
version = { workspace = true }
description = "HiGHS solver adapter for Arco targets"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
arco-contracts = { workspace = true }
arco-targets = { workspace = true }
arco-tools = { workspace = true }
highs = "1.8"
highs-sys = "1.12.1"
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
