from __future__ import annotations

from enum import Enum
from os import PathLike
from typing import (
    Callable,
    Iterator,
    Mapping,
    Sequence,
    TypeAlias,
    TypedDict,
    TypeVar,
    overload,
)

BlockFnT = TypeVar("BlockFnT", bound=Callable[..., object])

IndexMember: TypeAlias = int | float | str | tuple["IndexMember", ...]
JsonPrimitive: TypeAlias = None | bool | int | float | str
JsonValue: TypeAlias = JsonPrimitive | list["JsonValue"] | dict[str, "JsonValue"]
BoundValue: TypeAlias = float | Sequence[float] | Sequence[Sequence[float]]

class SolverInfo(TypedDict):
    solver: str
    version: str | None

class SolverRuntimeInfo(TypedDict):
    family: str
    requires_license: bool
    license_env_var: str | None
    runtime_env_var: str | None
    runtime_dir: str | None
    configured_license_path: str | None
    backend_enabled: bool

class CscExport(TypedDict):
    col_ptrs: Sequence[int]
    row_indices: Sequence[int]
    values: Sequence[float]
    shape: tuple[int, int]

class CrsExport(TypedDict):
    row_ptrs: Sequence[int]
    col_indices: Sequence[int]
    values: Sequence[float]
    shape: tuple[int, int]

class CooExport(TypedDict):
    rows: Sequence[int]
    cols: Sequence[int]
    values: Sequence[float]
    shape: tuple[int, int]

class ArcoError(Exception):
    code: str

def error_code(exc: BaseException) -> str | None: ...
def diagnostic_codes() -> dict[str, str]: ...

class ModelEmptyError(ArcoError): ...
class VariableInvalidIdError(ArcoError): ...
class VariableInvalidBoundsError(ArcoError): ...
class VariableNotFoundError(ArcoError): ...
class ConstraintInvalidIdError(ArcoError): ...
class ConstraintInvalidBoundsError(ArcoError): ...
class ConstraintNotFoundError(ArcoError): ...
class ObjectiveMissingError(ArcoError): ...
class ObjectiveAlreadySetError(ArcoError): ...
class SlackInvalidPenaltyError(ArcoError): ...
class SolverInfeasibleError(ArcoError): ...
class SolverUnboundedError(ArcoError): ...
class SolverTimeLimitError(ArcoError): ...
class SolverIterationLimitError(ArcoError): ...
class SolverInternalError(ArcoError): ...
class SolverNotAvailableError(ArcoError): ...
class CscInvalidDataError(ArcoError): ...
class ExprDivisionByZeroError(ArcoError): ...
class ExprNotSingleVariableError(ArcoError): ...
class ExprCoefficientError(ArcoError): ...
class ExprConstantOffsetError(ArcoError): ...
class ExprTypeError(ArcoError): ...
class ArrayShapeMismatchError(ArcoError): ...
class ArrayIndexError(ArcoError): ...
class ArrayTypeError(ArcoError): ...
class ArrayDimensionError(ArcoError): ...
class ArrayOverflowError(ArcoError): ...
class BlockArtifactError(ArcoError): ...
class BlockContractError(ArcoError): ...
class BlockResultError(ArcoError): ...
class LoggingConfigError(ArcoError): ...
class LoggingIoError(ArcoError): ...
class MetadataConversionError(ArcoError): ...
class ConstraintTypeError(ArcoError): ...
class ConstraintBoundsMissingError(ArcoError): ...
class ConstraintSenseError(ArcoError): ...
class SolverInvalidSettingError(ArcoError): ...
class SolverIndexError(ArcoError): ...
class SolverTypeError(ArcoError): ...
class IndexSetEmptyError(ArcoError): ...
class IndexSetTypeError(ArcoError): ...
class IndexSetArgumentError(ArcoError): ...
class IndexSetIndexError(ArcoError): ...
class BoundsInvalidError(ArcoError): ...
class SlackBoundError(ArcoError): ...
class SlackValueUnavailableError(ArcoError): ...
class CscDtypeError(ArcoError): ...
class CscDimensionError(ArcoError): ...
class CscContiguityError(ArcoError): ...
class CscNegativeIndexError(ArcoError): ...
class DependencyMissingError(ArcoError): ...
class ModelBinaryBoundsError(ArcoError): ...
class ObjectiveIndexError(ArcoError): ...

class Sense(Enum):
    MINIMIZE: Sense
    MAXIMIZE: Sense

class SimplifyLevel(Enum):
    NONE: SimplifyLevel
    LIGHT: SimplifyLevel

class SolutionStatus(Enum):
    OPTIMAL: SolutionStatus
    INFEASIBLE: SolutionStatus
    UNBOUNDED: SolutionStatus
    TIME_LIMIT: SolutionStatus
    ERROR: SolutionStatus

class BoundType(Enum):
    PositiveFloat: BoundType
    NegativeFloat: BoundType
    NonNegativeFloat: BoundType
    NonPositiveFloat: BoundType
    PositiveInt: BoundType
    NegativeInt: BoundType
    NonNegativeInt: BoundType
    NonPositiveInt: BoundType
    Binary: BoundType

PositiveFloat: BoundType
NegativeFloat: BoundType
NonNegativeFloat: BoundType
NonPositiveFloat: BoundType
PositiveInt: BoundType
NegativeInt: BoundType
NonNegativeInt: BoundType
NonPositiveInt: BoundType
Binary: BoundType

class Bounds:
    def __init__(
        self,
        *,
        lower: BoundValue | None = None,
        upper: BoundValue | None = None,
    ) -> None: ...
    @property
    def lower(self) -> BoundValue: ...
    @property
    def upper(self) -> BoundValue: ...

class Solver:
    def __init__(
        self,
        *,
        presolve: bool | None = None,
        threads: int | None = None,
        tolerance: float | None = None,
        time_limit: float | None = None,
        mip_gap: float | None = None,
        verbosity: int | None = None,
        log_to_console: bool | None = None,
        parameters: Mapping[str, str] | None = None,
        solver: str | None = None,
    ) -> None: ...
    @property
    def presolve(self) -> bool | None: ...
    @property
    def threads(self) -> int | None: ...
    @property
    def tolerance(self) -> float | None: ...
    @property
    def time_limit(self) -> float | None: ...
    @property
    def mip_gap(self) -> float | None: ...
    @property
    def verbosity(self) -> int | None: ...
    @property
    def log_to_console(self) -> bool | None: ...
    def copy(
        self,
        *,
        update: Mapping[str, bool | int | float | str | Mapping[str, str] | None]
        | None = None,
    ) -> Solver: ...

class SolverSelection:
    def __init__(self, token: str) -> None: ...
    @staticmethod
    def family(name: str) -> SolverSelection: ...
    @staticmethod
    def profile(name: str, *, family: str | None = None) -> SolverSelection: ...
    @property
    def token(self) -> str: ...

class SolverProfile:
    def __init__(
        self,
        name: str,
        family: str,
        transport: str | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def family(self) -> str: ...
    @property
    def transport(self) -> str: ...

class HiGHS(Solver):
    def __init__(
        self,
        *,
        presolve: bool | None = None,
        threads: int | None = None,
        tolerance: float | None = None,
        time_limit: float | None = None,
        mip_gap: float | None = None,
        verbosity: int | None = None,
        log_to_console: bool | None = None,
        parameters: Mapping[str, str] | None = None,
        solver: str | None = None,
    ) -> None: ...

@overload
def solver_runtime_info(*, family: str) -> SolverRuntimeInfo: ...
@overload
def solver_runtime_info(*, family: None = None) -> dict[str, SolverRuntimeInfo]: ...

class Xpress(Solver):
    def __init__(
        self,
        *,
        presolve: bool | None = None,
        threads: int | None = None,
        tolerance: float | None = None,
        time_limit: float | None = None,
        mip_gap: float | None = None,
        verbosity: int | None = None,
        log_to_console: bool | None = None,
        parameters: Mapping[str, str] | None = None,
        solver: str | None = None,
    ) -> None: ...

class Scip(Solver):
    def __init__(
        self,
        *,
        presolve: bool | None = None,
        threads: int | None = None,
        tolerance: float | None = None,
        time_limit: float | None = None,
        mip_gap: float | None = None,
        verbosity: int | None = None,
        log_to_console: bool | None = None,
        parameters: Mapping[str, str] | None = None,
        solver: str | None = None,
    ) -> None: ...

class IndexSet:
    def __init__(
        self,
        *,
        name: str,
        size: int | None = None,
        members: Sequence[IndexMember] | None = None,
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def members(self) -> list[IndexMember]: ...
    def __getitem__(self, index: int | slice) -> IndexMember | IndexSet: ...
    def __iter__(self) -> Iterator[IndexMember]: ...
    def alias(self, name: str) -> IndexSet: ...

class ParamArray:
    @property
    def axes(self) -> tuple[IndexSet, ...]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def values(self) -> object: ...
    @property
    def name(self) -> str | None: ...
    def __getitem__(self, index: object) -> object: ...
    def __add__(self, other: ParamArray | float | object) -> object: ...
    def __radd__(self, other: ParamArray | float | object) -> object: ...
    def __sub__(self, other: ParamArray | float | object) -> object: ...
    def __rsub__(self, other: ParamArray | float | object) -> object: ...
    def __mul__(self, other: ParamArray | float | object) -> object: ...
    def __rmul__(self, other: ParamArray | float | object) -> object: ...
    def __truediv__(self, other: ParamArray | float | object) -> object: ...
    def __rtruediv__(self, other: ParamArray | float | object) -> object: ...
    def __and__(self, other: ParamArray | object) -> object: ...
    def __or__(self, other: ParamArray | object) -> object: ...
    def __invert__(self) -> ParamArray: ...
    def __matmul__(self, other: IndexSet | Sequence[IndexSet]) -> object: ...
    def __rshift__(self, other: IndexSet | Sequence[IndexSet]) -> object: ...
    def sum(self, *, over: IndexSet | Sequence[IndexSet] | None = None) -> object: ...
    def cumsum(self, *, over: IndexSet) -> ParamArray: ...
    def diff(self, *, over: IndexSet) -> ParamArray: ...
    def roll(self, *, shift: int, over: IndexSet) -> ParamArray: ...

def param(
    values: object,
    *,
    axes: tuple[IndexSet, ...],
    name: str | None = None,
) -> ParamArray: ...

class Expr:
    def __init__(self) -> None: ...
    def scale(self, *, by: float) -> Expr: ...
    def add(self, *, other: Expr) -> Expr: ...
    def __add__(self, other: Expr | Variable | float) -> Expr: ...
    def __radd__(self, other: Expr | Variable | float) -> Expr: ...
    def __sub__(self, other: Expr | Variable | float) -> Expr: ...
    def __rsub__(self, other: Expr | Variable | float) -> Expr: ...
    def __mul__(self, other: float) -> Expr: ...
    def __rmul__(self, other: float) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __truediv__(self, other: float) -> Expr: ...
    def __ge__(self, rhs: Expr | Variable | float) -> ConstraintExpr: ...
    def __le__(self, rhs: Expr | Variable | float) -> ConstraintExpr: ...
    def __eq__(self, rhs: object) -> ConstraintExpr: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class ConstraintExpr:
    @property
    def expr(self) -> Expr: ...
    @property
    def sense(self) -> str: ...
    @property
    def rhs(self) -> float: ...

class Variable:
    @property
    def name(self) -> str | None: ...
    @property
    def bounds(self) -> Bounds: ...
    @property
    def is_integer(self) -> bool: ...
    @property
    def is_binary(self) -> bool: ...
    def __add__(self, other: Expr | Variable | float) -> Expr: ...
    def __radd__(self, other: Expr | Variable | float) -> Expr: ...
    def __sub__(self, other: Expr | Variable | float) -> Expr: ...
    def __rsub__(self, other: Expr | Variable | float) -> Expr: ...
    def __mul__(self, other: float) -> Expr: ...
    def __rmul__(self, other: float) -> Expr: ...
    def __neg__(self) -> Expr: ...
    def __truediv__(self, other: float) -> Expr: ...
    def __ge__(self, rhs: Expr | Variable | float) -> ConstraintExpr: ...
    def __le__(self, rhs: Expr | Variable | float) -> ConstraintExpr: ...
    def __eq__(self, rhs: object) -> ConstraintExpr: ...
    def __int__(self) -> int: ...
    def __index__(self) -> int: ...

class Constraint:
    @property
    def name(self) -> str | None: ...
    @property
    def bounds(self) -> Bounds: ...

class VariableArray:
    def __add__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __radd__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __sub__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __rsub__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __mul__(self, other: ParamArray | float | Sequence[float]) -> ExprArray: ...
    def __rmul__(self, other: ParamArray | float | Sequence[float]) -> ExprArray: ...
    def __truediv__(self, other: float) -> ExprArray: ...
    def __neg__(self) -> ExprArray: ...
    def __ge__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    def __le__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    def __eq__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    @property
    def variables(self) -> list[Variable]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def dense_count(self) -> int: ...
    @property
    def active_count(self) -> int: ...
    @property
    def index_sets(self) -> tuple[IndexSet, ...]: ...
    @property
    def values(self) -> list[Expr]: ...
    def memory_estimate(self) -> dict[str, object]: ...
    def flatten(self) -> list[Expr]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Variable | Expr]: ...
    def __getitem__(
        self, index: int | slice | tuple[object, ...] | object
    ) -> Variable | Expr | VariableArray: ...
    def sum(
        self, *, over: IndexSet | Sequence[IndexSet] | None = None
    ) -> Expr | ExprArray: ...
    def cumsum(self, *, over: IndexSet) -> Expr | ExprArray: ...
    def diff(self, *, over: IndexSet) -> Expr | ExprArray: ...
    def roll(self, *, shift: int, over: IndexSet) -> Expr | ExprArray: ...

class ExprArray:
    def __add__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __radd__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __sub__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __rsub__(
        self, other: VariableArray | ExprArray | ParamArray | float | Sequence[float]
    ) -> ExprArray: ...
    def __mul__(self, other: ParamArray | float | Sequence[float]) -> ExprArray: ...
    def __rmul__(self, other: ParamArray | float | Sequence[float]) -> ExprArray: ...
    def __truediv__(self, other: float) -> ExprArray: ...
    def __neg__(self) -> ExprArray: ...
    def __ge__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    def __le__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    def __eq__(
        self,
        rhs: VariableArray
        | ExprArray
        | ParamArray
        | float
        | Sequence[float]
        | IndexSet,
    ) -> ConstraintArray: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def index_sets(self) -> tuple[IndexSet, ...]: ...
    @property
    def values(self) -> list[Expr]: ...
    def memory_estimate(self) -> dict[str, object]: ...
    def flatten(self) -> list[Expr]: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[Expr]: ...
    def __getitem__(
        self, index: int | slice | tuple[object, ...] | object
    ) -> Expr | ExprArray: ...
    def sum(
        self, *, over: IndexSet | Sequence[IndexSet] | None = None
    ) -> Expr | ExprArray: ...
    def cumsum(self, *, over: IndexSet) -> Expr | ExprArray: ...
    def diff(self, *, over: IndexSet) -> Expr | ExprArray: ...
    def roll(self, *, shift: int, over: IndexSet) -> Expr | ExprArray: ...

class ConstraintArray:
    @property
    def sense(self) -> str: ...
    @property
    def rhs(self) -> list[float]: ...
    @property
    def shape(self) -> tuple[int, ...]: ...
    @property
    def index_sets(self) -> tuple[IndexSet, ...]: ...

class ConstraintIterator:
    def __iter__(self) -> Iterator[Constraint]: ...
    def __next__(self) -> Constraint: ...
    def __len__(self) -> int: ...

class VariableIterator:
    def __iter__(self) -> Iterator[Variable]: ...
    def __next__(self) -> Variable: ...
    def __len__(self) -> int: ...

class SlackHandle:
    @property
    def constraint_id(self) -> int: ...
    @property
    def bound(self) -> str: ...
    @property
    def penalty(self) -> float: ...
    @property
    def name(self) -> str | None: ...
    @property
    def var_ids(self) -> dict[str, int | None]: ...

class ElasticHandle:
    @property
    def lower(self) -> SlackHandle | None: ...
    @property
    def upper(self) -> SlackHandle | None: ...

class SlackVariable:
    @property
    def constraint(self) -> Constraint: ...
    @property
    def bound(self) -> str: ...
    @property
    def penalty(self) -> float: ...
    @property
    def name(self) -> str | None: ...
    @property
    def value(self) -> float: ...

class BlockPorts:
    def __getattr__(self, key: str) -> object: ...
    def keys(self) -> list[str]: ...

class BlockHandle:
    @property
    def name(self) -> str: ...
    @property
    def in_(self) -> BlockPorts: ...
    @property
    def out(self) -> BlockPorts: ...
    def input(self, key: str) -> object: ...
    def output(self, key: str) -> object: ...

class BlockResults:
    def __getitem__(self, key: str) -> SolveResult: ...
    def __len__(self) -> int: ...
    def __contains__(self, key: str) -> bool: ...
    def __iter__(self) -> Iterator[str]: ...
    def keys(self) -> list[str]: ...
    def get(self, key: str, default: object = None) -> SolveResult | object: ...
    def values(self) -> list[SolveResult]: ...
    def items(self) -> list[tuple[str, SolveResult]]: ...
    def statuses(self) -> dict[str, str]: ...
    def report(self) -> list[dict[str, object]]: ...
    def report_json(self) -> str: ...
    def diagnostics(self) -> list[dict[str, object]]: ...
    def diagnostics_json(self) -> str: ...
    def artifact_manifest(
        self, *, policy: str = "summary"
    ) -> list[dict[str, object]]: ...
    def artifact_manifest_json(self, *, policy: str = "summary") -> str: ...
    def write_artifacts(
        self,
        directory: str | PathLike[str],
        *,
        policy: str = "summary",
    ) -> list[dict[str, object]]: ...

class SolveResult:
    @property
    def status(self) -> SolutionStatus: ...
    @property
    def objective_value(self) -> float: ...
    @property
    def primal_values(self) -> list[float]: ...
    @property
    def variable_duals(self) -> list[float]: ...
    @property
    def constraint_duals(self) -> list[float]: ...
    @property
    def blocks(self) -> BlockResults | None: ...
    def value(self, variable: Variable | VariableArray) -> float | object: ...
    def dual(self, constraint: Constraint) -> float: ...
    def reduced_cost(self, variable: Variable) -> float: ...
    def slack(self, constraint: Constraint) -> float: ...
    def get_primal(self, *, index: int) -> float: ...
    def get_variable_dual(self, *, index: int) -> float: ...
    def get_constraint_dual(self, *, index: int) -> float: ...
    def is_optimal(self) -> bool: ...
    def is_feasible(self) -> bool: ...
    def is_infeasible(self) -> bool: ...
    def is_unbounded(self) -> bool: ...
    def status_string(self) -> str: ...
    def solve_time_seconds(self) -> float: ...

class VariableView:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def bounds(self) -> Bounds: ...
    @property
    def is_integer(self) -> bool: ...
    @property
    def is_active(self) -> bool: ...
    @property
    def metadata(self) -> JsonValue | None: ...

class ConstraintView:
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str | None: ...
    @property
    def bounds(self) -> Bounds: ...
    @property
    def nnz(self) -> int: ...
    @property
    def metadata(self) -> JsonValue | None: ...

class CoefficientView:
    @property
    def variable_id(self) -> int: ...
    @property
    def constraint_id(self) -> int: ...
    @property
    def value(self) -> float: ...

class ObjectiveView:
    @property
    def sense(self) -> str | None: ...
    @property
    def terms(self) -> list[tuple[int, float]]: ...
    @property
    def name(self) -> str | None: ...

class SlackView:
    @property
    def constraint_id(self) -> int: ...
    @property
    def bound(self) -> str: ...
    @property
    def penalty(self) -> float: ...
    @property
    def lower_variable(self) -> int | None: ...
    @property
    def upper_variable(self) -> int | None: ...
    @property
    def name(self) -> str | None: ...

class SnapshotMemoryEstimate:
    @property
    def coefficient_value_bytes(self) -> int: ...
    @property
    def coefficient_index_bytes(self) -> int: ...
    @property
    def variable_column_pointer_bytes(self) -> int: ...
    @property
    def sparse_matrix_bytes(self) -> int: ...

class SnapshotMetadata:
    @property
    def variables(self) -> int: ...
    @property
    def constraints(self) -> int: ...
    @property
    def coefficients(self) -> int: ...
    @property
    def memory(self) -> SnapshotMemoryEstimate: ...

class ModelSnapshot:
    @property
    def variables(self) -> list[VariableView]: ...
    @property
    def constraints(self) -> list[ConstraintView]: ...
    @property
    def coefficients(self) -> list[CoefficientView] | None: ...
    @property
    def objective(self) -> ObjectiveView | None: ...
    @property
    def slacks(self) -> list[SlackView] | None: ...
    @property
    def metadata(self) -> SnapshotMetadata: ...

class Model:
    def __init__(
        self,
        *,
        simplify_level: SimplifyLevel | None = None,
        solver: Solver | SolverSelection | SolverProfile | None = None,
    ) -> None: ...
    @classmethod
    def from_csc(
        cls,
        *,
        num_constraints: int,
        num_variables: int,
        col_ptrs: object,
        row_indices: object,
        values: object,
        var_lower: object,
        var_upper: object,
        con_lower: object,
        con_upper: object,
        is_integer: object,
        simplify_level: SimplifyLevel | None = None,
    ) -> Model: ...
    def reserve(
        self,
        *,
        num_variables: int = 0,
        num_constraints: int = 0,
    ) -> None: ...
    def add_variable(
        self,
        *,
        bounds: Bounds | BoundType,
        is_integer: bool = False,
        is_binary: bool = False,
        name: str | None = None,
    ) -> Variable: ...
    def add_variables(
        self,
        *,
        axes: tuple[IndexSet, ...],
        bounds: Bounds | BoundType,
        is_integer: bool = False,
        is_binary: bool = False,
        active: object | None = None,
        name: str | None = None,
    ) -> VariableArray: ...
    def add_constraint(
        self,
        expr: ConstraintExpr | Variable | Expr,
        *,
        bounds: Bounds | None = None,
        name: str | None = None,
    ) -> Constraint: ...
    def add_constraints(
        self,
        expr: ConstraintArray | VariableArray | ExprArray,
        *,
        sense: str = "ge",
        rhs: float | IndexSet | None = None,
        active: object | None = None,
        name: str | None = None,
    ) -> list[Constraint]: ...
    def add_slack(
        self,
        constraint: Constraint,
        *,
        bound: str,
        penalty: float,
        name: str | None = None,
    ) -> SlackVariable: ...
    def add_slacks(
        self,
        constraints: Sequence[Constraint],
        *,
        bound: str,
        penalty: float | Sequence[float],
        name: str | None = None,
    ) -> list[SlackVariable]: ...
    def make_elastic(
        self,
        constraint: Constraint,
        *,
        upper_penalty: float | None = None,
        lower_penalty: float | None = None,
        name: str | None = None,
    ) -> ElasticHandle: ...
    def set_coefficient(
        self, *, var_idx: int, constraint_idx: int, coeff: float
    ) -> None: ...
    def set_variable_name(self, *, index: int, name: str) -> None: ...
    def set_constraint_name(self, *, index: int, name: str) -> None: ...
    def set_objective(
        self,
        *,
        sense: Sense,
        terms: Sequence[tuple[int, float]],
        name: str | None = None,
    ) -> None: ...
    def minimize(
        self,
        expr: Expr | Variable | VariableArray | ExprArray,
        *,
        name: str | None = None,
    ) -> None: ...
    def maximize(
        self,
        expr: Expr | Variable | VariableArray | ExprArray,
        *,
        name: str | None = None,
    ) -> None: ...
    def solve(
        self,
        *,
        solver: Solver | SolverSelection | SolverProfile | None = None,
        log_to_console: bool | None = None,
        primal_start: Sequence[tuple[int, float]] | None = None,
        time_limit: float | None = None,
        mip_gap: float | None = None,
        verbosity: int | None = None,
    ) -> SolveResult: ...
    def inspect(
        self,
        *,
        include_coeffs: bool = False,
        include_slacks: bool = True,
        variable_ids: Sequence[int] | None = None,
        constraint_ids: Sequence[int] | None = None,
    ) -> ModelSnapshot: ...
    def pprint(self) -> None: ...
    def add_block(
        self,
        block_fn: Callable[..., object],
        *,
        name: str | None = None,
        data: object | None = None,
        extract: Callable[..., object],
    ) -> BlockHandle: ...
    def link(self, source: object, target: object) -> None: ...
    def list_constraints(self) -> ConstraintIterator: ...
    def list_variables(self) -> VariableIterator: ...
    def get_constraint(self, *, name: str) -> Constraint: ...
    def get_variable(self, *, name: str) -> Variable: ...
    def export_csc(self) -> CscExport: ...
    def export_crs(self) -> CrsExport: ...
    def export_coo(self) -> CooExport: ...
    @property
    def num_variables(self) -> int: ...
    @property
    def num_constraints(self) -> int: ...
    @property
    def nnz(self) -> int: ...
    @property
    def variables(self) -> list[Variable]: ...
    @property
    def constraints(self) -> list[Constraint]: ...
    @property
    def has_blocks(self) -> bool: ...

def solution_summary(result: SolveResult, *, verbose: bool = False) -> None: ...
def enable_logging(*, level: str | None = None) -> bool: ...
def solver_info() -> SolverInfo: ...
def block(
    func: BlockFnT | None = None, *, name: str | None = None
) -> BlockFnT | Callable[[BlockFnT], BlockFnT]: ...
