[package]
name = "arco-ipopt"
version = { workspace = true }
description = "IPOPT solver backend for Arco optimization"
edition = { workspace = true }
rust-version = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
authors = { workspace = true }
license-file = { workspace = true }
publish = false

[lints]
workspace = true

[dependencies]
arco-core = { workspace = true }
arco-expr = { workspace = true }
arco-solver = { workspace = true }
ipopt = "0.5"
tracing = { workspace = true }

[dev-dependencies]
tracing-subscriber = { workspace = true }
